name: Sync to Target Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          persist-credentials: true  # Maintain auth

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Target
        env:
          TARGET_REPO: "Meet98787/testrepo"
          PAT_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}  # Your PAT stored in secrets
        run: |
          # Add target remote
          git remote add target "https://oauth2:$PAT_TOKEN@github.com/$TARGET_REPO.git"
          
          # Verify remote
          git remote -v
          
          # Force push (--force-with-lease is safer)
          git push target HEAD:main --force-with-lease