name: Sync to pbdefi/pb-admin

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Re-clone target repo and push
        run: |
          # Clone the target repository to start fresh
          git clone git@github.com:Meet98787/testrepo.git
          cd testrepo
          
          # Copy all files from the checked-out source repository to the target repository
          cp -r ../* .
          
          # Stage, commit, and push
          git add .
          git commit -m "Sync updates"
          git push origin main --force
