name: Sync to pbdefi/pb-admin

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source repository
      - name: Checkout source repo
        uses: actions/checkout@v4
        name: Checkout source repository
        with:
          repository: <source-repository-name>  # Replace with actual source repo name

      # Set up SSH for secure communication with GitHub
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Clone the target repository
      - name: Clone target repository
        run: |
          git clone git@github.com:Meet98787/testrepo.git target_repo
          cd target_repo
          
          # Copy all files from the source repo to the target repo
          cp -r ../* .

          # Stage, commit, and push changes
          git add .
          git commit -m "Sync updates"
          git push origin main --force

