name: Sync to target repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source repository
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: MitLakhani9/admin-test
          fetch-depth: 0  # Get all history

      # Set up SSH for both repositories
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Add target repository as a remote
      - name: Add target repository
        run: |
          git remote add target git@github.com:Meet98787/testrepo.git
          git fetch target

      # Reset target's main branch to match source's main branch
      - name: Sync changes to target
        run: |
          # Create a temporary branch with the source's content
          git checkout -B temp-sync-branch origin/main
          
          # Force push to target's main branch
          git push target temp-sync-branch:main --force
          
          # Clean up
          git branch -D temp-sync-branch

      # Optional: Create a sync-branch instead of updating main directly
      - name: Create sync branch (alternative)
        if: false  # Set to true if you prefer creating branches instead of updating main
        run: |
          git checkout -B sync-branch origin/main
          git push target sync-branch --force