name: Sync to pbdefi/pb-admin

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Mirror to pbdefi/pb-admin
        run: |
          git config --global user.email "mit@workinfinity.com"
          git config --global user.name "MitLakhani9"
          
          # Add the remote
          git remote add target https://github.com/Meet98787/testrepo.git || true
          
          # Set the URL for the target remote
          git remote set-url target https://github.com/Meet98787/testrepo.git
          
          git config --global credential.helper store
          
          # Save the credentials in .git-credentials
          echo "https://MitLakhani9:${{ secrets.DEFI_REPO_TOKEN }}@github.com" > ~/.git-credentials
          
          # Push the changes
          git push target HEAD:main --force
