name: Secure Repository Sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch main

      - name: Prepare and Push Content
        env:
          TARGET_REPO: "Meet98787/testrepo"
          PAT_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          # Create temporary directory
          WORK_DIR=$(mktemp -d)
          cd $WORK_DIR
          
          # Initialize new repository
          git init .
          
          # Copy all files except workflow
          find "$GITHUB_WORKSPACE" -mindepth 1 -maxdepth 1 \
            ! -name '.github' \
            ! -name '.git' \
            -exec cp -r {} . \;
          
          # Create initial commit
          git add .
          git commit -m "Sync from source repository [$(date +%Y-%m-%d)]"
          
          # Push using token authentication (alternative method)
          git push \
            "https://x-access-token:$PAT_TOKEN@github.com/$TARGET_REPO.git" \
            HEAD:main --force
          
          # Clean up
          cd ..
          rm -rf $WORK_DIR