name: Sync to Target Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror Repository
        env:
          TARGET_REPO: "Meet98787/testrepo"
          PAT_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          # Create temporary directory
          mkdir -p /tmp/mirror
          cd /tmp/mirror

          # Clone source repo with full history
          git clone --mirror "https://github.com/MitLakhani9/admin-test.git" .

          # Push to target repo using PAT
          git push --mirror "https://${{ github.actor }}:$PAT_TOKEN@github.com/$TARGET_REPO.git"

          # Clean up
          cd ..
          rm -rf mirror