name: Sync to Target Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Target
        env:
          TARGET_REPO: "Meet98787/testrepo"
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          # Remove any existing remote
          git remote remove target || true
          
          # Add authenticated remote
          git remote add target "https://oauth2:${TARGET_TOKEN}@github.com/${TARGET_REPO}.git"
          
          # Verify remote
          git remote -v
          
          # Force push (use --force-with-lease for safety)
          git push target HEAD:main --force