name: Sync to pbdefi/pb-admin

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Mirror to pbdefi/pb-admin
        run: |
          git config --global user.email "mit@workinfinity.com"
          git config --global user.name "MitLakhani9"
          git remote set-url target https://github.com/Meet98787/testrepo.git
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.DEFI_REPO_TOKEN }}" > ~/.git-credentials
          git push target HEAD:main --force
