name: Sync to Target Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Sync via GitHub API
        env:
          SOURCE_REPO: MitLakhani9/admin-test
          TARGET_REPO: Meet98787/testrepo
          PAT_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          # Get current commit SHA from source
          COMMIT_SHA=$(git rev-parse HEAD)

          # Create a new commit in target repo using API
          curl -X POST \
            -H "Authorization: token $PAT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_REPO/git/commits" \
            -d '{
              "message": "Sync from $SOURCE_REPO",
              "tree": "$(curl -s -H "Authorization: token $PAT_TOKEN" "https://api.github.com/repos/$SOURCE_REPO/git/commits/$COMMIT_SHA" | jq -r '.tree.sha')",
              "parents": ["$(curl -s -H "Authorization: token $PAT_TOKEN" "https://api.github.com/repos/$TARGET_REPO/git/refs/heads/main" | jq -r '.object.sha')"]
            }'

          # Update target's main branch
          curl -X PATCH \
            -H "Authorization: token $PAT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_REPO/git/refs/heads/main" \
            -d '{
              "sha": "$NEW_COMMIT_SHA",
              "force": true
            }'