name: Sync to pbdefi/pb-admin

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Re-clone repository and push
        run: |
          # Clone the target repository again to start fresh
          git clone git@github.com:Meet98787/testrepo.git
          cd testrepo
          # Copy the contents of the source repository into the target repo
          cp -r /path/to/your/source/* .
          git add .
          git commit -m "Sync updates"
          git push origin main --force
