name: Repository Synchronization

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for efficiency
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch main

      - name: Mirror with History
        run: |
          git clone --mirror https://github.com/MitLakhani9/admin-test.git
          cd admin-test.git
          git -c http.extraheader="Authorization: bearer $PAT_TOKEN" \
          push --mirror https://github.com/$TARGET_REPO.git

      - name: Prepare and Push Content
        env:
          TARGET_REPO: "Meet98787/testrepo"
          PAT_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          # Create temporary directory
          WORK_DIR=$(mktemp -d)
          cd $WORK_DIR
          
          # Initialize new repository
          git init .
          
          # Copy all files from source
          cp -r $GITHUB_WORKSPACE/. .
          
          # Remove workflow file to avoid PAT exposure
          rm -f .github/workflows/sync-to-pb-admin.yml
          
          # Create initial commit
          git add .
          git commit -m "Sync from source repository"
          
          # Add target remote
          git remote add target https://github.com/$TARGET_REPO.git
          
          # Push using header authentication
          git -c http.extraheader="Authorization: bearer $PAT_TOKEN" \
              push target HEAD:main --force
          
          # Clean up
          cd ..
          rm -rf $WORK_DIR