name: Sync to pbdefi/pb-admin

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source repository
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: MitLakhani9/admin-test  # Replace with actual source repo name

      # Set up SSH for secure communication with GitHub
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Add target repository as a remote
      - name: Add target repository as remote
        run: |
          git remote add target git@github.com:Meet98787/testrepo.git

      # Push source repo's changes to the target repository
      - name: Push to target repository
        run: |
          # Fetch the latest changes from the target repository
          git fetch target
          
          # Push changes from the source repository to the target repository
          git push target main --force
