name: Sync to target repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: List remotes (debug)
        run: git remote -v
        
      - name: Push to target
        run: |
          git remote add target https://${{ github.actor }}:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Meet98787/testrepo.git
          git push target HEAD:main --force