name: Secure Repository Sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch main

      - name: Create Clean Mirror
        env:
          TARGET_REPO: "Meet98787/testrepo"
          PAT_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          # Create temporary workspace
          WORKSPACE=$(mktemp -d)
          cd $WORKSPACE
          
          # Clone source without history
          git clone --depth 1 https://github.com/MitLakhani9/admin-test.git source
          cd source
          
          # Create new orphan branch with clean history
          git checkout --orphan temp-sync-branch
          git rm -rf .
          git add -A
          git commit -m "Initial sync commit"
          
          # Push to target using header authentication
          git remote add target https://github.com/$TARGET_REPO.git
          git -c http.extraheader="AUTHORIZATION: bearer $PAT_TOKEN" push target temp-sync-branch:main --force
          
          # Clean up
          cd /tmp
          rm -rf $WORKSPACE