name: Repository Sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          persist-credentials: false  # Important for clean auth

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Git Authentication
        env:
          PAT_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          # Store credentials in git config
          git config --global credential.helper store
          echo "https://oauth2:$PAT_TOKEN@github.com" > ~/.git-credentials

      - name: Mirror Repository
        env:
          TARGET_REPO: "Meet98787/testrepo"
        run: |
          # Create temporary bare repository
          git init --bare /tmp/mirror
          cd /tmp/mirror
          
          # Add both remotes
          git remote add source https://github.com/MitLakhani9/admin-test.git
          git remote add target https://github.com/$TARGET_REPO.git
          
          # Fetch all from source
          git fetch --all
          
          # Push everything to target
          git push --mirror target
          
          # Clean up
          cd /tmp
          rm -rf mirror