name: Sync to target repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: MitLakhani9/admin-test
          fetch-depth: 0

      - name: Sync to target repo
        run: |
          git remote add target https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Meet98787/testrepo.git
          git fetch target
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Meet98787/testrepo.git HEAD:main --force