name: Sync to Target Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror Repository (Secure)
        env:
          TARGET_REPO: "Meet98787/testrepo"
          PAT_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          # Create fresh temporary directory
          WORK_DIR=$(mktemp -d)
          cd $WORK_DIR

          # Clone with token in environment (not in command)
          git -c "http.https://github.com.extraheader=AUTHORIZATION: basic $(echo -n "x-access-token:$PAT_TOKEN" | base64)" \
            clone --mirror "https://github.com/MitLakhani9/admin-test.git" .

          # Push with header authentication
          git -c "http.https://github.com.extraheader=AUTHORIZATION: basic $(echo -n "x-access-token:$PAT_TOKEN" | base64)" \
            push --mirror "https://github.com/$TARGET_REPO.git"

          # Clean up
          cd ..
          rm -rf $WORK_DIR